# ----------- CONFIGURABLE START -----------
title:            "Jaydeep Deshpande"
description:      "About me"
url:              https://jaydeep.info # Site url, without a slash at the end.
signoff:          "jaydeep" # Your name
share:            true # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"