# ----------- CONFIGURABLE START -----------
title:            "Jaydeep Deshpande"
description:      "About me"
url:              https://jaydeep.info # Site url, without a slash at the end.
signoff:          "jaydeep" # Your name
share:            true # Turn on twitter and facebook share buttons

links:
  - name:         About me
    url:          /about
    external:     false
  - name:         Articles
    url:          /articles
    external:     false
  - name:         Books
    url:          /books
    external:     false
  - name:         Clean Tech
    url:          /cleantech
    external:     false
  - name:         Coffee
    url:          /coffee
    external:     false
  - name:         Learning
    url:          /learning
    external:     false
  - name:         Blog
    url:          /blog
    external:     false
# ------------ CONFIGURABLE END ------------

collections:
  posts:
    output: true
    permalink: /blog/:title
  coffee:
    output: true
    permalink: /coffee/:title
  cleantech:
    output: true
    permalink: /cleantech/:title
  learning:
    output: true
    permalink: /learning/:title
defaults:
  - scope:
      path: "" # Applies to all files
    values:
      layout: default